site_name: Home Lab Documentation

repo_url: https://github.com/vcaldas/homelab
repo_name: Homelab
theme:
  name: material

nav:
  - Home: README.md
  - Ansible:
    - Playbooks:
      - Proxmox: proxmox.md
    - Roles:
      - Server Baseline: roles/server_baseline.md
      - Proxmox Template VM: roles/proxmox_template_vm.md
  - Infrastructure:
    - VLANs: vlans.md
    - Sudoers Setup: setup_sudoers.md