[project]
name = "homelab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13   "
dependencies = [
    "ansible>=13.3.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
]
