
---
- name: Set var for desired distro
  ansible.builtin.set_fact:
    distro: "{{ item | lower }}"

- name: Ensure distro is supported
  ansible.builtin.assert:
    that: distro in "{{ proxmox_template_vm_supported_distros }}"
    fail_msg: "Unsupported Distro! See https://galaxy.ansible.com/ui/repo/published/joshrnoll/homelab/content/role/proxmox_template_vm/"

- name: Create VM template
  ansible.builtin.include_tasks: deploy_template.yml

- name: Pause 10 seconds to avoid file locks with slow storage
  ansible.builtin.pause:
    seconds: 10
  when: proxmox_template_vm_slow_storage is true
