galaxy_info:
  author: Victor Caldas

  description: Baseline configuration for Ubuntu and Fedora machines

  license: MIT

  min_ansible_version: 2.16.9

  galaxy_tags:
    - homelab
    - tailscale
    - ubuntu
    - fedora
    - debian
    - infrastructure
    - linux
    - baseline

dependencies: []