---
- name: Ensure desired user exists with sudo privileges
  become: true
  ansible.builtin.user:
    name: "{{ server_baseline_created_username }}"
    state: present
    groups: wheel
    append: true
    create_home: true

- name: Update dnf and install default system packages
  become: true
  ansible.builtin.dnf:
    pkg: "{{ server_baseline_fedora_packages_default }}"
    state: present
    update_cache: true

- name: Install additional system packages
  become: true
  ansible.builtin.dnf:
    pkg: "{{ server_baseline_fedora_packages }}"
    state: present
  when: server_baseline_fedora_packages is defined

- name: Ensure firewalld is running and enabled
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Set default zone to 'FedoraServer'
  become: true
  ansible.builtin.command: firewall-cmd --set-default-zone=FedoraServer
  register: default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

- name: Allow SSH access
  become: true
  ansible.posix.firewalld:
    zone: FedoraServer
    service: ssh
    state: enabled
    permanent: true
    immediate: true

- name: Setup passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized key for created user
  become: true
  ansible.posix.authorized_key:
    user: "{{ server_baseline_created_username }}"
    state: present
    key: "{{ server_baseline_ssh_key }}"

- name: Disable SSH password auth
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: Restart SSH daemon

- name: Disable password authentication for root
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  notify: Restart SSH daemon

- name: Set time zone
  become: true
  community.general.timezone:
    name: "{{ server_baseline_timezone }}"

- name: Install and bring up Tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale.machine
  vars:
    tailscale_authkey: "{{ server_baseline_tailscale_oauth_client_secret }}"
    tailscale_tags:
      - "servers"
    tailscale_oauth_ephemeral: false
    tailscale_oauth_preauthorized: true
    no_log: false
...