---
- name: Ensure required variables are provided
  ansible.builtin.assert:
    that:
      - server_baseline_created_username is defined
      - server_baseline_tailscale_oauth_client_secret is defined
    fail_msg: "One or more required variables are missing. See https://github.com/joshrnoll/ansible-collection-homelab/tree/main/roles/server_baseline"
    quiet: true

- name: Check OS type
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in supported_distributions
    fail_msg: "Unsupported OS. See https://github.com/joshrnoll/ansible-collection-homelab/tree/main/roles/docker_setup"
    quiet: true

- name: Check for Proxmox hosts
  ansible.builtin.set_fact:
    include_proxmox: true
  when: ansible_facts['virtualization_role'] == "host" and ansible_facts['distribution'] == "Debian"

- name: Server baseline for Ubuntu machines
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Server baseline for Debian machines
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['distribution'] == "Debian"

# - name: Server baseline for Fedora machines
#   ansible.builtin.include_tasks: fedora.yml
#   when: ansible_facts['distribution'] == "Fedora"

- name: Server baseline for Proxmox hosts
  ansible.builtin.include_tasks: proxmox.yml
  when: include_proxmox is true
...